# Basic background info on Git

Many people think of Github as a dropbox for code.
While this is relatively far from the truth it is not entirely inacurate.
If so then Github is a dropbox on speed. 

## What is Git?

- distributed version-control system
- most widely used modern version control system in the world
- most recognized and popular approach to contribute to a project
- not just for code but for any text-based projects

---

## Why use git?

- Version control
- Keep track of how a project evolved
- Undo mistakes
- Maintain alternative versions
- Test new features without breaking anything
- Private Collaboration (within lab or with collaborators)
- Public collaboration (with the research field)
- Decentralized i.e. you don't have to be connected to a server to use git (unlike google docs or overleaf)
- Git encourages the use of a transparant and reviewed workflow

---

## Limitations

- Git only works "properly" with text based file-types. 
- Any file can be tracked
- Git will only be able to display and merge changes for text-based files
- The git history includes copies of all past versions so larger file types blow up your repository 
- Git is not a backup-system (unless you also upload your repository to a remote server) 
- If you deleted a repository it is gone

---

## Typical text based research file types that work well with git

- *.txt (Textfiles)   
- *.R    (R File)
- *.Rmd  (R Markdown document)
- *.csv  (Comma delimited value files)
- *.tex  (Latex files)
- *.bib  (Bibliography files)
- *.sps  (SPSS analysis scripts)

---

### Caveat
Depending on when you start managing a project as a git repository collaborators or people on the internet can see every single change you have ever made to the file.
Unfortunately, this has been used against people in the past.  / 

While I advocate a transparent research process, you might be taken aback by this level of transparency.

There are ways to prevent this. 
- Only upload a close to final version to github  
- Collaborate on private repositories and create a new public repository once the project is in a presentable state (It doesn't actually need to be a new repository. You can also rebase the project to hide past steps)  
- Write a disclaimer in the readme that the amount of project contribution cannot be inferred from the project history.  

The option I prefer and recommend is going public from the get go and mainly working on a work-in-progress-branch.
Branches on public repositories are also public. The default view, however, is the master branch. Most researchers who are not advanced git users won't even know about branches and those who don't won't bother checking then out. More on branches [here](#branches) 

---

### Is it for me?
- Do you have several versions of something but no idea what the difference between them is or how they evolved?
- Do you find yourself copying large sections of code to play with it, try something our wihtout breaking what you already accomplished?
- Have you ever changed something in multiple parts of your code only to figure out that that was a bad idea and the first aproach was better?
- Have you ever worked on code with multiple people and have no idea who wrote a specific part?
